SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) AS PRICE
  FROM USED_GOODS_BOARD UGB
  JOIN USED_GOODS_USER UGU
    ON UGB.WRITER_ID = UGU.USER_ID
 WHERE UGB.STATUS = 'DONE'
 GROUP BY UGU.USER_ID, UGU.NICKNAME
HAVING SUM(UGB.PRICE) >= 700000
 ORDER BY PRICE;