SELECT CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR CRCR
  LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
 USING (CAR_ID)
 WHERE CRCR.CAR_TYPE = '세단'
   AND EXTRACT(MONTH FROM CRCRH.START_DATE) = 10
 GROUP BY CAR_ID
 ORDER BY CAR_ID DESC;