SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, B.SCORE
FROM REST_INFO A
JOIN (
        SELECT RI.REST_ID, ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
        FROM REST_INFO RI
        JOIN REST_REVIEW RR
        ON RI.REST_ID = RR.REST_ID
        WHERE RI.ADDRESS LIKE '서울%'
        GROUP BY RI.REST_ID
) B
ON A.REST_ID = B.REST_ID
ORDER BY B.SCORE DESC, A.FAVORITES DESC