SELECT * 
FROM (
SELECT FLAVOR
FROM (
    SELECT FLAVOR, TOTAL_ORDER
FROM FIRST_HALF FH
UNION
SELECT FLAVOR, TOTAL_ORDER
FROM JULY J
    ) A
GROUP BY FLAVOR   
ORDER BY SUM(TOTAL_ORDER) DESC
    )
    WHERE ROWNUM <= 3