SELECT FLAVOR
FROM (
    SELECT J.FLAVOR, SUM(FH.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF FH
    RIGHT JOIN JULY J
    ON FH.FLAVOR = J.FLAVOR
    GROUP BY J.FLAVOR
    ORDER BY TOTAL DESC
)
WHERE ROWNUM <= 3;