SELECT *
FROM (
    SELECT AI.ANIMAL_ID, AI.NAME
      FROM ANIMAL_INS AI
      JOIN ANIMAL_OUTS AO
        ON AI.ANIMAL_ID = AO.ANIMAL_ID 
     ORDER BY AO.DATETIME - AI.DATETIME DESC
     )
 WHERE ROWNUM <= 2;