SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
  FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
      FROM REST_INFO
      GROUP BY FOOD_TYPE
      ) A
  JOIN REST_INFO RI
   ON A.FOOD_TYPE = RI.FOOD_TYPE
  AND A.FAVORITES = RI.FAVORITES
ORDER BY RI.FOOD_TYPE DESC;
      