SELECT CAR_ID,
    CASE
        WHEN EXISTS (
            SELECT 1
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
             WHERE H2.CAR_ID = H1.CAR_ID
               AND TO_DATE('2022-10-16', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE      
        ) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
 FROM (
        SELECT DISTINCT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
       ) H1
ORDER BY CAR_ID DESC

-- SELECT *
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
-- ORDER BY CAR_ID, START_DATE