SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
 WHERE CAR_ID IN (
    SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
     WHERE START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
     GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
 ) 
   AND START_DATE BETWEEN TO_DATE('2022-08-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
 GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
 ORDER BY MONTH, CAR_ID DESC
 
-- SELECT TO_CHAR(START_DATE, 'MM') AS MONTH, CAR_ID
--   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--   ORDER BY CAR_ID, START_DATE

 --  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
 -- WHERE START_DATE BETWEEN TO_DATE('2022-08', 'YYYY-MM') AND TO_DATE('2022-10', 'YYYY-MM') 
 -- GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
 -- ORDER BY MONTH, CAR_ID
 
 -- SELECT *
 --    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 --   ORDER BY CAR_ID, START_DATE
 