SELECT 
    EXTRACT(YEAR FROM OS.SALES_DATE) AS YEAR, 
    EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH,
    UI.GENDER, 
    COUNT(DISTINCT OS.USER_ID) AS USERS
FROM USER_INFO UI
JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY 
    EXTRACT(YEAR FROM OS.SALES_DATE), 
    EXTRACT(MONTH FROM OS.SALES_DATE), 
    UI.GENDER
ORDER BY YEAR, MONTH, UI.GENDER